version: "3"
services:
  app:
    build:
      context: .
      args:
        - uid=${uid:-1000}
    command: bash -x -c 'makepkg -s -f -i --noconfirm && makepkg --printsrcinfo > .SRCINFO && namcap xremap-*.pkg.tar.xz'
    volumes:
      - .:/app
